SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
anchor: configuration-step-3-scheduler-table
copyrights:
- Copyright (C) 2026 embedded brains GmbH & Co. KG
enabled-by: true
label: ConfigurationSchedulerTable
links:
- role: reference-location
  uid: ../c-user
name: Configuration Step 3 - Scheduler Table
path: config/scheduler-clustered.html
type: reference-location
