SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
brief: |
  Brief TODO.
copyrights:
- Copyright (C) 2026 embedded brains GmbH & Co. KG
definition:
  default:
    attributes: null
    body: null
    params:
    - const ${/c/if/pthread_condattr_t:/name} *${.:/params[0]/name}
    - int *${.:/params[1]/name}
    return: int
  variants: []
description: null
enabled-by: true
index-entries: []
interface-type: function
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: group
name: pthread_condattr_getpshared
notes: null
params:
- description: null
  dir: null
  name: __attr
- description: null
  dir: null
  name: __pshared
return: null
type: interface
