# SPDX-License-Identifier: BSD-2-Clause

# Copyright (C) 2026 embedded brains GmbH & Co. KG

RTEMS_API ?= 6
RTEMS_CPU ?= aarch64
RTEMS_BSP ?= zynqmp_apu
RTEMS_TOOLS ?= $(CURDIR)/work-tools/$(RTEMS_API)
RTEMS_ROOT ?= $(CURDIR)/work-rtems

QEMU = $(RTEMS_TOOLS)/bin/qemu-system-aarch64 -nographic -serial mon:stdio -machine virt,gic-version=3 -cpu cortex-a53 -m 4096 -kernel

PKG_CONFIG = $(RTEMS_ROOT)/lib/pkgconfig/$(RTEMS_CPU)-rtems$(RTEMS_API)-$(RTEMS_BSP).pc
BUILDDIR = b-$(RTEMS_CPU)-$(RTEMS_BSP)

DEPFLAGS = -MT $@ -MD -MP -MF $(basename $@).d
WARNFLAGS = -Wall -Wextra
OPTFLAGS = -O2 -g -ffunction-sections -fdata-sections
EXEEXT = .exe

ABI_FLAGS := $(shell pkg-config --define-variable=prefix=$(RTEMS_ROOT) --cflags $(PKG_CONFIG))
LDFLAGS := $(shell pkg-config --define-variable=prefix=$(RTEMS_ROOT) --variable=LDFLAGS $(PKG_CONFIG))
CPPFLAGS = -Itestsuites/validation
CFLAGS = $(DEPFLAGS) $(WARNFLAGS) $(ABI_FLAGS) $(OPTFLAGS)
CXXFLAGS = $(DEPFLAGS) $(WARNFLAGS) $(ABI_FLAGS) $(OPTFLAGS)
ASFLAGS = $(ABI_FLAGS)

CCLINK = $(CC) $(CFLAGS) -Wl,-Map,$(basename $@).map
CXXLINK = $(CXX) $(CXXFLAGS) -Wl,-Map,$(basename $@).map

ABI_FLAGS += --coverage -fprofile-info-section=.rtemsroset.gcov_info.content -fprofile-update=atomic
LDFLAGS += -Wl,--wrap=_CPU_Fatal_halt -Wl,--wrap=bsp_reset -Wl,--start-group -lrtemsbsp -lrtemscpu -lrtemstest -lgcov -Wl,--end-group

$(BUILDDIR)/%.o: %.c | $(BUILDDIR)
	$(CC) $(CPPFLAGS) $(CFLAGS) -c $< -o $@

$(BUILDDIR)/%.o: %.S | $(BUILDDIR)
	$(CC) $(CPPFLAGS) -DASM $(CFLAGS) -c $< -o $@

$(BUILDDIR)/%.o: %.cc | $(BUILDDIR)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $< -o $@

$(BUILDDIR)/%.o: %.cpp | $(BUILDDIR)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $< -o $@

$(BUILDDIR)/%.o: %.s | $(BUILDDIR)
	$(AS) $(ASFLAGS) $< -o $@

export PATH := $(RTEMS_TOOLS)/bin:$(PATH)

export AR = $(RTEMS_CPU)-rtems$(RTEMS_API)-ar
export AS = $(RTEMS_CPU)-rtems$(RTEMS_API)-as
export CC = $(RTEMS_CPU)-rtems$(RTEMS_API)-gcc
export CXX = $(RTEMS_CPU)-rtems$(RTEMS_API)-g++
export LD = $(RTEMS_CPU)-rtems$(RTEMS_API)-ld
export NM = $(RTEMS_CPU)-rtems$(RTEMS_API)-nm
export OBJCOPY = $(RTEMS_CPU)-rtems$(RTEMS_API)-objcopy
export RANLIB = $(RTEMS_CPU)-rtems$(RTEMS_API)-ranlib
export SIZE = $(RTEMS_CPU)-rtems$(RTEMS_API)-size
export STRIP = $(RTEMS_CPU)-rtems$(RTEMS_API)-strip

APP = $(BUILDDIR)/example$(EXEEXT)

APP_OBJS =
APP_OBJS += $(BUILDDIR)/testsuites/validation/tc-flsl.o
APP_OBJS += $(BUILDDIR)/work/ts-work.o
APP_OBJS += $(BUILDDIR)/testsuites/validation/tx-support.o
APP_OBJS += $(BUILDDIR)/testsuites/validation/tx-timecounter.o

all: $(APP)

$(BUILDDIR):
	mkdir -p $(BUILDDIR)/cpukit/posix/src
	mkdir -p $(BUILDDIR)/cpukit/rtems/src
	mkdir -p $(BUILDDIR)/cpukit/score/src
	mkdir -p $(BUILDDIR)/testsuites/validation
	mkdir -p $(BUILDDIR)/work

testsuites/validation/tc-flsl.c: spec/c/req/flsl.yml
	uv run specwareexport $@

view:
	uv run specwareview --filter=action-table /c/req/flsl

$(APP): $(APP_OBJS)
	$(CCLINK) $^ $(LDFLAGS) -o $@

run: $(APP)
	$(QEMU) $< -no-reboot

coverage: $(APP)
	$(QEMU) $< -no-reboot | tee work-log.txt
	uv run specgcovr -o $(BUILDDIR) -d work-coverage -g $(RTEMS_TOOLS)/bin/$(RTEMS_CPU)-rtems$(RTEMS_API)-gcov -t $(RTEMS_TOOLS)/bin/$(RTEMS_CPU)-rtems$(RTEMS_API)-gcov-tool work-log.txt

qemu: $(APP)
	$(QEMU) $< -s -S

gdb: $(APP)
	$(RTEMS_TOOLS)/bin/gdb --command=work/$(RTEMS_CPU).gdb $<

clean:
	rm -rf $(BUILDDIR) work-log.txt work-coverage

-include $(APP_OBJS:%.o=%.d)
