# SPDX-License-Identifier: BSD-2-Clause

# Copyright (C) 2026 embedded brains GmbH & Co. KG

name: Sisyphos
on:
  workflow_run:
    workflows:
    - Zerberus
    types:
    - completed
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
        - aarch64
        - arm
        - i386
        - m68k
        - microblaze
        - mips
        - moxie
        - nios2
        - or1k
        - powerpc
        - riscv
        - sparc
        - x86_64
    env:
      TOOLS_ARCH: ${{ matrix.arch }}
    steps:
    - uses: actions/checkout@v6
    - name: Set up Python
      uses: actions/setup-python@v6
    - name: Set up uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true
        version: 0.11.9
    - name: Restore tools cache
      id: restore-tools
      uses: actions/cache/restore@v5
      with:
        path: tools
        key: tools-${{ matrix.arch }}-${{ hashFiles('build_tools.py', 'spec-pkg-tools/**/*.yml') }}
    - name: Build tools
      if: ${{ steps.restore-tools.outputs.cache-hit != 'true' }}
      run: |
        sudo apt-get update
        sudo apt-get -y install binutils-multiarch build-essential git gnutls-dev meson libglib2.0-dev libpixman-1-dev libssl-dev ninja-build
        make tools >log-tools.txt 2>&1
    - name: Tools log tail
      if: ${{ !cancelled() && steps.restore-tools.outputs.cache-hit != 'true' }}
      run: |
        tail -n 1000 log-tools.txt
    - name: Tools log artifact
      uses: actions/upload-artifact@v7
      if: ${{ !cancelled() && steps.restore-tools.outputs.cache-hit != 'true' }}
      with:
        name: log-tools-${{ matrix.arch }}
        path: log-tools.txt
        overwrite: true
    - name: Save tools cache
      id: save-tools
      uses: actions/cache/save@v5
      if: ${{ steps.restore-tools.outputs.cache-hit != 'true' }}
      with:
        path: tools
        key: tools-${{ matrix.arch }}-${{ hashFiles('build_tools.py', 'spec-pkg-tools/**/*.yml') }}
    - name: Cache build
      id: cache-build
      uses: actions/cache@v5
      with:
        path: build
        key: build-${{ matrix.arch }}-${{ hashFiles('build_tools.py', 'spec-pkg-tools/**/*.yml') }}
    - name: Make
      run: |
        make bsps >log-bsps.txt 2>&1
    - name: BSPs log tail
      if: ${{ !cancelled() }}
      run: |
        tail -n 1000 log-bsps.txt
    - name: BSPs log artifact
      uses: actions/upload-artifact@v7
      if: ${{ !cancelled() }}
      with:
        name: log-bsps-${{ matrix.arch }}
        path: log-bsps.txt
        overwrite: true
